CREATE DATABASE STUDY

USE STUDY

CREATE TABLE WEATHER_STATION (
	ID bigint IDENTITY(1, 1) NOT NULL,
	[CODE] varchar(4) NOT NULL,
	[NAME] varchar(255) NOT NULL,
	[STATE] varchar(2) NOT NULL,
	ALTITUDE float,
	LATITUDE decimal(8, 6) NOT NULL,
	LONGITUDE decimal(9, 6) NOT NULL,
	COORDINATE AS geography::Point(LATITUDE, LONGITUDE, 4326),
	FOUNDED_AT date NOT NULL,
	CREATED_AT datetime NOT NULL CONSTRAINT DF__WEATHER_STATION__CREATED_AT DEFAULT GETDATE(),

	CONSTRAINT PK__WEATHER_STATION__ID PRIMARY KEY (ID)
)

CREATE TABLE WEATHER_STATION_READING (
	ID bigint IDENTITY(1, 1) NOT NULL,
	STATION_ID bigint NOT NULL,
	PRECIPITATION float,
	PRESSURE float,
	RADIATION float,
	DRY_AIR_TEMPERATURE float,
	WET_AIR_TEMPERATURE float,
	RELATIVE_HUMIDITY float,
	WIND_DIRECTION float,
	WIND_GUST float,
	WIND_SPEED float,
	[TIMESTAMP] datetimeoffset NOT NULL,
	CREATED_AT datetime NOT NULL CONSTRAINT DF__WEATHER_STATION_READING__CREATED_AT DEFAULT GETDATE(),

	CONSTRAINT PK__WEATHER_STATION_READING__ID PRIMARY KEY (ID),
	CONSTRAINT FK__WEATHER_STATION_READING__STATION_ID FOREIGN KEY (STATION_ID) REFERENCES WEATHER_STATION(ID),
	INDEX IX__WEATHER_STATION_READING__STATION_ID (STATION_ID)
)

CREATE VIEW WEATHER_STATION_READING_CHANGE
AS
	WITH T AS (
		SELECT
			LAG(ID) OVER (
				PARTITION BY STATION_ID
				ORDER BY [TIMESTAMP]
			) AS PREVIOUS_ID,
			*
		FROM WEATHER_STATION_READING
	)
	SELECT
		[CURRENT].ID,
		[CURRENT].STATION_ID,
		[CURRENT].PRECIPITATION,
		ABS([CURRENT].PRECIPITATION - PREVIOUS.PRECIPITATION) AS PRECIPITATION_CHANGE,
		[CURRENT].PRESSURE,
		ABS([CURRENT].PRESSURE - PREVIOUS.PRESSURE) AS PRESSURE_CHANGE,
		[CURRENT].RADIATION,
		ABS([CURRENT].RADIATION - PREVIOUS.RADIATION) AS RADIATION_CHANGE,
		[CURRENT].DRY_AIR_TEMPERATURE,
		ABS([CURRENT].DRY_AIR_TEMPERATURE - PREVIOUS.DRY_AIR_TEMPERATURE) AS DRY_AIR_TEMPERATURE_CHANGE,
		[CURRENT].WET_AIR_TEMPERATURE,
		ABS([CURRENT].WET_AIR_TEMPERATURE - PREVIOUS.WET_AIR_TEMPERATURE) AS WET_AIR_TEMPERATURE_CHANGE,
		[CURRENT].RELATIVE_HUMIDITY,
		ABS([CURRENT].RELATIVE_HUMIDITY - PREVIOUS.RELATIVE_HUMIDITY) AS RELATIVE_HUMIDITY_CHANGE,
		[CURRENT].WIND_DIRECTION,
		[CURRENT].WIND_GUST,
		[CURRENT].WIND_SPEED,
		[CURRENT].[TIMESTAMP]
	FROM T AS [CURRENT]
	LEFT JOIN T AS PREVIOUS
		ON [CURRENT].PREVIOUS_ID = PREVIOUS.ID

CREATE VIEW WEATHER_STATION_READING_METRIC
AS
	SELECT
		STATION_ID,
		SUM(PRECIPITATION) AS TOTAL_PRECIPITATION,
		MAX(PRECIPITATION_CHANGE) AS MAXIMUM_PRECIPITATION_CHANGE,
		MIN(PRESSURE) AS MINIMUM_PRESSURE,
		AVG(PRESSURE) AS AVERAGE_PRESSURE,
		MAX(PRESSURE) AS MAXIMUM_PRESSURE,
		MAX(PRESSURE_CHANGE) AS MAXIMUM_PRESSURE_CHANGE,
		SUM(RADIATION) AS TOTAL_RADIATION,
		MAX(RADIATION) AS MAXIMUM_RADIATION,
		MAX(RADIATION_CHANGE) AS MAXIMUM_RADIATION_CHANGE,
		MIN(DRY_AIR_TEMPERATURE) AS MINIMUM_DRY_AIR_TEMPERATURE,
		AVG(DRY_AIR_TEMPERATURE) AS AVERAGE_DRY_AIR_TEMPERATURE,
		MAX(DRY_AIR_TEMPERATURE) AS MAXIMUM_DRY_AIR_TEMPERATURE,
		MAX(DRY_AIR_TEMPERATURE_CHANGE) AS MAXIMUM_DRY_AIR_TEMPERATURE_CHANGE,
		MIN(WET_AIR_TEMPERATURE) AS MINIMUM_WET_AIR_TEMPERATURE,
		AVG(WET_AIR_TEMPERATURE) AS AVERAGE_WET_AIR_TEMPERATURE,
		MAX(WET_AIR_TEMPERATURE) AS MAXIMUM_WET_AIR_TEMPERATURE,
		MAX(WET_AIR_TEMPERATURE_CHANGE) AS MAXIMUM_WET_AIR_TEMPERATURE_CHANGE,
		MIN(RELATIVE_HUMIDITY) AS MINIMUM_RELATIVE_HUMIDITY,
		AVG(RELATIVE_HUMIDITY) AS AVERAGE_RELATIVE_HUMIDITY,
		MAX(RELATIVE_HUMIDITY) AS MAXIMUM_RELATIVE_HUMIDITY,
		MAX(RELATIVE_HUMIDITY_CHANGE) AS MAXIMUM_RELATIVE_HUMIDITY_CHANGE,
		MAX(WIND_GUST) AS MAXIMUM_WIND_GUST,
		MAX(WIND_SPEED) AS MAXIMUM_WIND_SPEED,
		CAST([TIMESTAMP] AS date) AS REFERENCE_DATE
	FROM WEATHER_STATION_READING_CHANGE
	GROUP BY
		STATION_ID,
		CAST([TIMESTAMP] AS date)
