SELECT
	ID AS STATION_ID,
	CODE,
	[NAME],
	[STATE],
	ALTITUDE,
	LATITUDE,
	LONGITUDE,
	FOUNDED_AT
FROM WEATHER_STATION

SELECT
	STATION_ID,
	PRECIPITATION,
	PRESSURE,
	RADIATION,
	DRY_AIR_TEMPERATURE,
	WET_AIR_TEMPERATURE,
	RELATIVE_HUMIDITY,
	WIND_DIRECTION,
	WIND_GUST,
	WIND_SPEED,
	CONVERT(varchar, CAST([TIMESTAMP] AS datetime), 126) AS [TIMESTAMP]
FROM WEATHER_STATION_READING
