/*
	DROP TABLE IF EXISTS #INTEREST_POINT
	DROP TABLE IF EXISTS #INTEREST_POINT_WEATHER_STATION
*/

CREATE TABLE #INTEREST_POINT (
	ID bigint IDENTITY(1, 1) NOT NULL,
	[NAME] varchar(255) NOT NULL,
	LATITUDE decimal(8, 6) NOT NULL,
	LONGITUDE decimal(9, 6) NOT NULL,
	COORDINATE AS geography::Point(LATITUDE, LONGITUDE, 4326),
	CREATED_AT datetime NOT NULL CONSTRAINT DF__INTEREST_POINT__CREATED_AT DEFAULT GETDATE(),

	CONSTRAINT PK__INTEREST_POINT__ID PRIMARY KEY (ID)
)

INSERT INTO #INTEREST_POINT ([NAME], LATITUDE, LONGITUDE) VALUES
	('MASP', -23.561670, -46.656015),
	('Estágio', -23.552674, -46.658228),
	('Fundação', -23.548108, -46.632963),
	('Memórias de outra vida', -23.993453, -46.201984),
	('Oásis', -22.412453, -47.523687),
	('Primeiro amor', -25.581080, -49.396755)
	
SELECT *
INTO #INTEREST_POINT_WEATHER_STATION
FROM (
	SELECT
		[IP].ID AS INTEREST_POINT_ID,
		WS.ID AS WEATHER_STATION_ID,
		ROW_NUMBER() OVER (
			PARTITION BY [IP].ID
			ORDER BY [IP].COORDINATE.STDistance(WS.COORDINATE)
		) AS [CLASSIFICATION],
		[IP].COORDINATE.STDistance(WS.COORDINATE) AS DISTANCE
	FROM #INTEREST_POINT AS [IP]
	CROSS JOIN WEATHER_STATION AS WS
) AS T
WHERE [CLASSIFICATION] <= 3
ORDER BY
	INTEREST_POINT_ID,
	[CLASSIFICATION]
