/*
	DROP VIEW IF EXISTS WEATHER_STATION_READING_METRIC
*/

CREATE VIEW WEATHER_STATION_READING_METRIC
AS
	SELECT
		STATION_ID,
		SUM(PRECIPITATION) AS TOTAL_PRECIPITATION,
		MAX(PRECIPITATION_CHANGE) AS MAXIMUM_PRECIPITATION_CHANGE,
		MIN(PRESSURE) AS MINIMUM_PRESSURE,
		AVG(PRESSURE) AS AVERAGE_PRESSURE,
		MAX(PRESSURE) AS MAXIMUM_PRESSURE,
		MAX(PRESSURE_CHANGE) AS MAXIMUM_PRESSURE_CHANGE,
		SUM(RADIATION) AS TOTAL_RADIATION,
		MAX(RADIATION) AS MAXIMUM_RADIATION,
		MAX(RADIATION_CHANGE) AS MAXIMUM_RADIATION_CHANGE,
		MIN(DRY_AIR_TEMPERATURE) AS MINIMUM_DRY_AIR_TEMPERATURE,
		AVG(DRY_AIR_TEMPERATURE) AS AVERAGE_DRY_AIR_TEMPERATURE,
		MAX(DRY_AIR_TEMPERATURE) AS MAXIMUM_DRY_AIR_TEMPERATURE,
		MAX(DRY_AIR_TEMPERATURE_CHANGE) AS MAXIMUM_DRY_AIR_TEMPERATURE_CHANGE,
		MIN(WET_AIR_TEMPERATURE) AS MINIMUM_WET_AIR_TEMPERATURE,
		AVG(WET_AIR_TEMPERATURE) AS AVERAGE_WET_AIR_TEMPERATURE,
		MAX(WET_AIR_TEMPERATURE) AS MAXIMUM_WET_AIR_TEMPERATURE,
		MAX(WET_AIR_TEMPERATURE_CHANGE) AS MAXIMUM_WET_AIR_TEMPERATURE_CHANGE,
		MIN(RELATIVE_HUMIDITY) AS MINIMUM_RELATIVE_HUMIDITY,
		AVG(RELATIVE_HUMIDITY) AS AVERAGE_RELATIVE_HUMIDITY,
		MAX(RELATIVE_HUMIDITY) AS MAXIMUM_RELATIVE_HUMIDITY,
		MAX(RELATIVE_HUMIDITY_CHANGE) AS MAXIMUM_RELATIVE_HUMIDITY_CHANGE,
		MAX(WIND_GUST) AS MAXIMUM_WIND_GUST,
		MAX(WIND_SPEED) AS MAXIMUM_WIND_SPEED,
		CAST([TIMESTAMP] AS date) AS REFERENCE_DATE
	FROM WEATHER_STATION_READING_CHANGE
	GROUP BY
		STATION_ID,
		CAST([TIMESTAMP] AS date)
