/*
	DROP TABLE IF EXISTS WEATHER_STATION_READING
	DROP TABLE IF EXISTS WEATHER_STATION
*/

CREATE TABLE WEATHER_STATION (
	ID bigint IDENTITY(1, 1) NOT NULL,
	[CODE] varchar(4) NOT NULL,
	[NAME] varchar(255) NOT NULL,
	[STATE] varchar(2) NOT NULL,
	ALTITUDE float,
	LATITUDE decimal(8, 6) NOT NULL,
	LONGITUDE decimal(9, 6) NOT NULL,
	COORDINATE AS geography::Point(LATITUDE, LONGITUDE, 4326),
	FOUNDED_AT date NOT NULL,
	CREATED_AT datetime NOT NULL CONSTRAINT DF__WEATHER_STATION__CREATED_AT DEFAULT GETDATE(),

	CONSTRAINT PK__WEATHER_STATION__ID PRIMARY KEY (ID)
)

CREATE TABLE WEATHER_STATION_READING (
	ID bigint IDENTITY(1, 1) NOT NULL,
	STATION_ID bigint NOT NULL,
	PRECIPITATION float,
	PRESSURE float,
	RADIATION float,
	DRY_AIR_TEMPERATURE float,
	WET_AIR_TEMPERATURE float,
	RELATIVE_HUMIDITY float,
	WIND_DIRECTION float,
	WIND_GUST float,
	WIND_SPEED float,
	[TIMESTAMP] datetimeoffset NOT NULL,
	CREATED_AT datetime NOT NULL CONSTRAINT DF__WEATHER_STATION_READING__CREATED_AT DEFAULT GETDATE(),

	CONSTRAINT PK__WEATHER_STATION_READING__ID PRIMARY KEY (ID),
	CONSTRAINT FK__WEATHER_STATION_READING__STATION_ID FOREIGN KEY (STATION_ID) REFERENCES WEATHER_STATION(ID),

	INDEX IX__WEATHER_STATION_READING__STATION_ID (STATION_ID),
    INDEX IX__WEATHER_STATION_READING__TIMESTAMP ([TIMESTAMP])
)
