/*
	DROP VIEW IF EXISTS WEATHER_STATION_READING_CHANGE
*/

CREATE VIEW WEATHER_STATION_READING_CHANGE
AS
	WITH T AS (
		SELECT
			LAG(ID) OVER (
				PARTITION BY STATION_ID
				ORDER BY [TIMESTAMP]
			) AS PREVIOUS_ID,
			*
		FROM WEATHER_STATION_READING
	)
	SELECT
		[CURRENT].ID,
		[CURRENT].STATION_ID,
		[CURRENT].PRECIPITATION,
		ABS([CURRENT].PRECIPITATION - PREVIOUS.PRECIPITATION) AS PRECIPITATION_CHANGE,
		[CURRENT].PRESSURE,
		ABS([CURRENT].PRESSURE - PREVIOUS.PRESSURE) AS PRESSURE_CHANGE,
		[CURRENT].RADIATION,
		ABS([CURRENT].RADIATION - PREVIOUS.RADIATION) AS RADIATION_CHANGE,
		[CURRENT].DRY_AIR_TEMPERATURE,
		ABS([CURRENT].DRY_AIR_TEMPERATURE - PREVIOUS.DRY_AIR_TEMPERATURE) AS DRY_AIR_TEMPERATURE_CHANGE,
		[CURRENT].WET_AIR_TEMPERATURE,
		ABS([CURRENT].WET_AIR_TEMPERATURE - PREVIOUS.WET_AIR_TEMPERATURE) AS WET_AIR_TEMPERATURE_CHANGE,
		[CURRENT].RELATIVE_HUMIDITY,
		ABS([CURRENT].RELATIVE_HUMIDITY - PREVIOUS.RELATIVE_HUMIDITY) AS RELATIVE_HUMIDITY_CHANGE,
		[CURRENT].WIND_DIRECTION,
		[CURRENT].WIND_GUST,
		[CURRENT].WIND_SPEED,
		[CURRENT].[TIMESTAMP]
	FROM T AS [CURRENT]
	LEFT JOIN T AS PREVIOUS
		ON [CURRENT].PREVIOUS_ID = PREVIOUS.ID
